#!/usr/bin/env python3
"""Compare selected rd2 exercises using World-Relative Product Gini.

This is a robustness diagnostic, not a replacement for the original exercise
outputs. It keeps the world-relative measure export-only and uses the balanced
2000-2024 panel generated by ``run_world_relative_product_gini.py``.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import run_country_size_effect as cse  # noqa: E402
from trade_concentration_pipeline import sample_processed_path, sample_results_dir  # noqa: E402
from run_world_relative_product_gini import artifact_stem, metric_alias_column, tables_dirname, zero_weight_column  # noqa: E402


COUNTRY_SAMPLE = "rd2_countries"
FLOW_CHOICES = ("Exports", "Imports")
OUTPUT_DIRNAMES = {
    "Exports": "world_relative_exercise_robustness",
    "Imports": "world_relative_import_exercise_robustness",
}
COUNTRY_SIZE_TERMS = ["log_population", "log_gdp_per_capita"]
GROWTH_LEVEL_TERM = "lag_log_real_exports"
GROWTH_POP_TERM = "lag_log_population"
E2_OUTCOME = "annualized_export_growth_log"


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def validate_unique(df: pd.DataFrame, keys: list[str], label: str) -> None:
    missing = sorted(set(keys) - set(df.columns))
    if missing:
        raise RuntimeError(f"{label} is missing key columns: {missing}")
    dupes = int(df.duplicated(keys).sum())
    if dupes:
        examples = df[df.duplicated(keys, keep=False)][keys].head(10).to_dict(orient="records")
        raise RuntimeError(f"{label} has duplicate keys on {keys}: {examples}")


def world_outcomes(flow: str) -> tuple[tuple[str, str], ...]:
    standard_metric = "standard_product_gini" if flow == "Exports" else "standard_import_product_gini"
    relative_metric = "world_relative_product_gini" if flow == "Exports" else "world_relative_import_product_gini"
    return (
        ("product_gini", standard_metric),
        (metric_alias_column(flow), relative_metric),
    )


def load_world_relative(country_sample: str, flow: str) -> pd.DataFrame:
    stem = artifact_stem(flow)
    path = sample_results_dir(country_sample) / tables_dirname(flow) / f"{stem}_all_years.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing world-relative Gini panel: {path}")
    df = pd.read_csv(path)
    metric_col = metric_alias_column(flow)
    zero_col = zero_weight_column(flow)
    required = {
        "country",
        "iso3",
        "reporter_code",
        "year",
        "flow",
        "world_relative_product_gini",
        metric_col,
        "world_weighted_share_gini",
        "active_product_gini",
        "metric_valid",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise RuntimeError(f"World-relative panel is missing columns: {missing}")
    df = df[df["flow"].eq(flow) & df["metric_valid"].astype(bool)].copy()
    df["reporter_code"] = pd.to_numeric(df["reporter_code"], errors="coerce").astype("Int64")
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
    df = df.dropna(subset=["reporter_code", "year"]).copy()
    df["reporter_code"] = df["reporter_code"].astype(int)
    df["year"] = df["year"].astype(int)
    validate_unique(df, ["reporter_code", "year"], "world-relative panel")
    keep_cols = [
        "reporter_code",
        "year",
        "world_relative_product_gini",
        metric_col,
        "world_weighted_share_gini",
        "active_product_gini",
        "country_active_products",
        zero_col,
    ]
    keep_cols = list(dict.fromkeys(keep_cols))
    return df[keep_cols].copy()


def load_flow_panel(path: Path, label: str, flow: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing {label}: {path}")
    panel = pd.read_parquet(path)
    if "flow" in panel.columns:
        panel = panel[panel["flow"].eq(flow)].copy()
    if "variant" in panel.columns:
        panel = panel[panel["variant"].eq("baseline")].copy()
    panel["reporter_code"] = pd.to_numeric(panel["reporter_code"], errors="coerce").astype("Int64")
    panel["year"] = pd.to_numeric(panel["year"], errors="coerce").astype("Int64")
    panel = panel.dropna(subset=["reporter_code", "year"]).copy()
    panel["reporter_code"] = panel["reporter_code"].astype(int)
    panel["year"] = panel["year"].astype(int)
    return panel


def merge_world(panel: pd.DataFrame, world: pd.DataFrame, label: str) -> pd.DataFrame:
    out = panel.merge(world, on=["reporter_code", "year"], how="inner", validate="many_to_one")
    if out.empty:
        raise RuntimeError(f"{label} has no rows after merging the world-relative panel.")
    return out


def model_frame(results: list[cse.ModelResult]) -> pd.DataFrame:
    return cse.model_results_to_frame(results)


def run_country_size_models(panel: pd.DataFrame, flow: str) -> pd.DataFrame:
    results: list[cse.ModelResult] = []
    for outcome, metric in world_outcomes(flow):
        for model_label, fixed_effects, two_way in [
            ("country_size_year_fe", ["year"], None),
            ("country_size_two_way_cluster", ["year"], "year"),
        ]:
            results.append(
                cse.run_ols_model(
                    panel,
                    outcome,
                    COUNTRY_SIZE_TERMS,
                    fixed_effects,
                    model_label,
                    COUNTRY_SAMPLE,
                    flow,
                    "product",
                    metric,
                    cluster_col="reporter_code",
                    two_way_cluster_col=two_way,
                )
            )
    out = model_frame(results)
    out.insert(0, "exercise_family", "country_size")
    return out


def run_growth_models(panel: pd.DataFrame, flow: str) -> pd.DataFrame:
    results: list[cse.ModelResult] = []
    specs = [
        ("growth_prior_country_year_fe", "prior_export_growth"),
        ("growth_contemporaneous_country_year_fe", "contemporaneous_export_growth"),
        ("growth_future_placebo_country_year_fe", "future_export_growth"),
    ]
    for outcome, metric in world_outcomes(flow):
        for model_label, growth_term in specs:
            results.append(
                cse.run_ols_model(
                    panel,
                    outcome,
                    [growth_term, GROWTH_LEVEL_TERM, GROWTH_POP_TERM],
                    ["reporter_code", "year"],
                    model_label,
                    COUNTRY_SAMPLE,
                    flow,
                    "product",
                    metric,
                    cluster_col="reporter_code",
                )
            )
    out = model_frame(results)
    out.insert(0, "exercise_family", "growth_effect")
    return out


def run_exercise2_growth_models(panel: pd.DataFrame) -> pd.DataFrame:
    rows: list[cse.ModelResult] = []
    work = panel.copy()
    work["product_gini_x_partner_gini"] = pd.to_numeric(work["product_gini"], errors="coerce") * pd.to_numeric(
        work["partner_gini"], errors="coerce"
    )
    work["world_relative_product_gini_x_partner_gini"] = pd.to_numeric(
        work["world_relative_product_gini"], errors="coerce"
    ) * pd.to_numeric(work["partner_gini"], errors="coerce")
    for horizon in sorted(work["horizon"].dropna().unique()):
        horizon_panel = work[work["horizon"].eq(horizon)].copy()
        for product_term, interaction, metric in [
            ("product_gini", "product_gini_x_partner_gini", "standard_product_gini"),
            (
                "world_relative_product_gini",
                "world_relative_product_gini_x_partner_gini",
                "world_relative_product_gini",
            ),
        ]:
            rows.append(
                cse.run_ols_model(
                    horizon_panel,
                    E2_OUTCOME,
                    [product_term, "partner_gini", interaction, "log_initial_exports", "oil_export_share"],
                    ["reporter_code", "year"],
                    f"e2_continuous_gini_h{int(horizon)}",
                    COUNTRY_SAMPLE,
                    "Exports",
                    "product",
                    metric,
                    cluster_col="reporter_code",
                )
            )
    out = model_frame(rows)
    out.insert(0, "exercise_family", "exercise_02_growth")
    return out


def load_ex11_country_year() -> pd.DataFrame:
    path = sample_processed_path("exercise_11_product_export_linkage_panel.parquet", COUNTRY_SAMPLE)
    if not path.exists():
        raise FileNotFoundError(f"Missing Exercise 11 product panel: {path}")
    cols = [
        "reporter_code",
        "year",
        "country",
        "iso3",
        "import_value",
        "total_imports",
        "is_intermediate",
        "loo_gini_contribution",
        "total_import_product_gini",
    ]
    product = pd.read_parquet(path, columns=cols)
    product["import_value"] = pd.to_numeric(product["import_value"], errors="coerce").fillna(0.0)
    product["is_intermediate"] = pd.to_numeric(product["is_intermediate"], errors="coerce").fillna(0).astype(int)
    product["loo_gini_contribution"] = pd.to_numeric(product["loo_gini_contribution"], errors="coerce").fillna(0.0)
    product["positive_loo_gini_contribution"] = product["loo_gini_contribution"].clip(lower=0)
    product["intermediate_import_value"] = product["import_value"] * product["is_intermediate"]
    product["intermediate_positive_loo_gini_contribution"] = (
        product["positive_loo_gini_contribution"] * product["is_intermediate"]
    )
    grouped = (
        product.groupby(["reporter_code", "year"], as_index=False)
        .agg(
            country=("country", "first"),
            iso3=("iso3", "first"),
            total_imports_from_products=("import_value", "sum"),
            intermediate_imports=("intermediate_import_value", "sum"),
            positive_loo_gini_contribution=("positive_loo_gini_contribution", "sum"),
            intermediate_positive_loo_gini_contribution=("intermediate_positive_loo_gini_contribution", "sum"),
            total_import_product_gini=("total_import_product_gini", "first"),
            active_import_products=("import_value", "size"),
        )
        .reset_index(drop=True)
    )
    grouped["intermediate_import_share"] = grouped["intermediate_imports"] / grouped["total_imports_from_products"]
    grouped["intermediate_positive_loo_share"] = np.where(
        grouped["positive_loo_gini_contribution"] > 0,
        grouped["intermediate_positive_loo_gini_contribution"] / grouped["positive_loo_gini_contribution"],
        np.nan,
    )
    grouped["log_total_imports"] = np.where(
        grouped["total_imports_from_products"] > 0, np.log(grouped["total_imports_from_products"]), np.nan
    )
    return grouped


def run_intermediate_import_models(panel: pd.DataFrame, flow: str) -> pd.DataFrame:
    results: list[cse.ModelResult] = []
    specs = [
        (
            "ex11_aggregate_import_structure_year_fe",
            ["total_import_product_gini", "intermediate_import_share", "log_total_imports"],
            ["year"],
        ),
        (
            "ex11_aggregate_import_structure_country_year_fe",
            ["total_import_product_gini", "intermediate_import_share", "log_total_imports"],
            ["reporter_code", "year"],
        ),
        (
            "ex11_aggregate_positive_loo_share_country_year_fe",
            ["intermediate_positive_loo_share", "total_import_product_gini", "log_total_imports"],
            ["reporter_code", "year"],
        ),
    ]
    for outcome, metric in world_outcomes(flow):
        for model_label, terms, fixed_effects in specs:
            results.append(
                cse.run_ols_model(
                    panel,
                    outcome,
                    terms,
                    fixed_effects,
                    model_label,
                    COUNTRY_SAMPLE,
                    flow,
                    "product",
                    metric,
                    cluster_col="reporter_code",
                )
            )
    out = model_frame(results)
    out.insert(0, "exercise_family", "exercise_11_intermediate_imports")
    return out


def key_coefficients(all_models: pd.DataFrame) -> pd.DataFrame:
    interest_terms = {
        "country_size": {"log_population"},
        "growth_effect": {"prior_export_growth", "contemporaneous_export_growth", "future_export_growth"},
        "exercise_02_growth": {
            "product_gini",
            "world_relative_product_gini",
            "world_relative_import_product_gini",
            "partner_gini",
            "product_gini_x_partner_gini",
            "world_relative_product_gini_x_partner_gini",
            "world_relative_import_product_gini_x_partner_gini",
        },
        "exercise_11_intermediate_imports": {
            "total_import_product_gini",
            "intermediate_import_share",
            "intermediate_positive_loo_share",
        },
    }
    pieces = []
    for family, terms in interest_terms.items():
        mask = all_models["exercise_family"].eq(family) & all_models["term"].isin(terms)
        pieces.append(all_models.loc[mask].copy())
    out = pd.concat(pieces, ignore_index=True)
    out["significant_5pct"] = pd.to_numeric(out["p_value"], errors="coerce") < 0.05
    out["family_bh_q_value"] = np.nan
    for family, idx in out.groupby("exercise_family").groups.items():
        out.loc[idx, "family_bh_q_value"] = cse.benjamini_hochberg(pd.to_numeric(out.loc[idx, "p_value"], errors="coerce"))
    out["family_bh_significant_5pct"] = pd.to_numeric(out["family_bh_q_value"], errors="coerce") < 0.05
    return out


def sample_diagnostics(frames: dict[str, pd.DataFrame], flow: str) -> pd.DataFrame:
    metric_col = metric_alias_column(flow)
    rows: list[dict[str, Any]] = []
    for name, df in frames.items():
        rows.append(
            {
                "sample": name,
                "rows": int(len(df)),
                "countries": int(df["reporter_code"].nunique()) if "reporter_code" in df.columns else np.nan,
                "year_min": int(df["year"].min()) if "year" in df.columns and not df.empty else np.nan,
                "year_max": int(df["year"].max()) if "year" in df.columns and not df.empty else np.nan,
                "world_relative_nonmissing": int(df.get(metric_col, pd.Series(dtype=float)).notna().sum()),
                "standard_product_nonmissing": int(df.get("product_gini", pd.Series(dtype=float)).notna().sum()),
            }
        )
    return pd.DataFrame(rows)


def format_model_row(row: pd.Series) -> str:
    coef = row.get("coefficient")
    se = row.get("std_error")
    p_value = row.get("p_value")
    nobs = row.get("nobs")
    clusters = row.get("clusters")
    return (
        f"{coef:.4f} (se {se:.4f}, p {p_value:.3g}, "
        f"n {int(nobs):,}, clusters {int(clusters)})"
    )


def write_memo(
    path: Path,
    key: pd.DataFrame,
    diagnostics: pd.DataFrame,
    output_paths: dict[str, Path],
    flow: str,
) -> None:
    relative_metric = "world_relative_product_gini" if flow == "Exports" else "world_relative_import_product_gini"
    relative_title = "World-Relative Product Gini" if flow == "Exports" else "World-Relative Import Product Gini"
    standard_metric = "standard_product_gini" if flow == "Exports" else "standard_import_product_gini"
    def one(family: str, metric: str, model_label: str, term: str) -> pd.Series | None:
        match = key[
            key["exercise_family"].eq(family)
            & key["metric"].eq(metric)
            & key["model_label"].eq(model_label)
            & key["term"].eq(term)
        ]
        if match.empty:
            return None
        return match.iloc[0]

    cs_std = one("country_size", standard_metric, "country_size_year_fe", "log_population")
    cs_wr = one("country_size", relative_metric, "country_size_year_fe", "log_population")
    gr_std = one("growth_effect", standard_metric, "growth_prior_country_year_fe", "prior_export_growth")
    gr_wr = one("growth_effect", relative_metric, "growth_prior_country_year_fe", "prior_export_growth")
    ex11_share = one(
        "exercise_11_intermediate_imports",
        relative_metric,
        "ex11_aggregate_import_structure_country_year_fe",
        "intermediate_import_share",
    )
    ex11_loo = one(
        "exercise_11_intermediate_imports",
        relative_metric,
        "ex11_aggregate_positive_loo_share_country_year_fe",
        "intermediate_positive_loo_share",
    )

    lines = [
        "# World-Relative Product Gini Exercise Robustness" if flow == "Exports" else "# World-Relative Import Product Gini Exercise Robustness",
        "",
        f"Generated: {now_utc()}",
        "",
        "## Purpose",
        "",
        (
            "This diagnostic asks whether selected rd2 results look different when export Product Gini is replaced by World-Relative Product Gini. The world-relative measure is export-only, converted to HS1992/H0 with official LT/HGL weights, balanced over 2000-2024, and uses leave-one-out world product weights. HS6 `999999` is excluded upstream before aggregation."
            if flow == "Exports"
            else "This diagnostic asks whether selected rd2 results look different when import Product Gini is replaced by World-Relative Import Product Gini. The import world-relative measure is import-only, converted to HS1992/H0 with official LT/HGL weights, balanced over 2000-2024, and uses leave-one-out world import product weights. HS6 `999999` is excluded upstream before aggregation."
        ),
        "",
        "## Bottom Line",
        "",
        f"- Country size: compares standard {flow.lower()} Product Gini with {relative_title} on the common balanced sample.",
        f"- Growth effect: uses the existing export-growth controls with {flow.lower()} concentration outcomes; for imports this is cross-flow descriptive evidence, not an import-growth design.",
        "- Exercise 2 growth buckets/continuous concentration: included only for the export world-relative run because the source panel is export-only.",
        f"- Intermediate-import/product-linkage exercise: aggregate import-structure predictors are related to the country-year {relative_title} outcome; this is not a product-level replacement.",
        "",
        "## Key Coefficients",
        "",
    ]
    if cs_std is not None and cs_wr is not None:
        lines.extend(
            [
                "Country size, main year-FE model; term is `log_population`:",
                "",
                f"- Standard Product Gini: {format_model_row(cs_std)}",
                f"- World-Relative Product Gini: {format_model_row(cs_wr)}",
                "",
            ]
        )
    if gr_std is not None and gr_wr is not None:
        lines.extend(
            [
                "Growth effect, country-year FE model; term is `prior_export_growth`:",
                "",
                f"- Standard Product Gini: {format_model_row(gr_std)}",
                f"- World-Relative Product Gini: {format_model_row(gr_wr)}",
                "",
            ]
        )
    if ex11_share is not None and ex11_loo is not None:
        lines.extend(
            [
                f"Intermediate-import aggregate follow-up; outcome is {relative_title}:",
                "",
                f"- `intermediate_import_share` with country and year FE: {format_model_row(ex11_share)}",
                f"- `intermediate_positive_loo_share` with country and year FE: {format_model_row(ex11_loo)}",
                "",
            ]
        )
    lines.extend(
        [
            "## Sample Diagnostics",
            "",
            diagnostics.to_markdown(index=False),
            "",
            "## Interpretation",
            "",
            "World-Relative Product Gini is a better benchmarked export-concentration outcome, but it is still a country-year aggregate. It can replace export Product Gini in country-year exercises such as country size and growth. It cannot directly replace product-level export outcomes in Exercise 11, because Exercise 11 asks whether specific import products map to specific export products.",
            "",
            "## Outputs",
            "",
        ]
    )
    for label, out_path in output_paths.items():
        lines.append(f"- {label}: `{rel(out_path)}`")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(args: argparse.Namespace) -> None:
    flow = args.flow
    result_dir = sample_results_dir(args.country_sample) / OUTPUT_DIRNAMES[flow]
    result_dir.mkdir(parents=True, exist_ok=True)

    world = load_world_relative(args.country_sample, flow)

    country_size_base = load_flow_panel(sample_processed_path("country_size_effect_panel.parquet", args.country_sample), "country size panel", flow)
    country_size = merge_world(country_size_base, world, "country size")

    growth_base = load_flow_panel(sample_processed_path("growth_effect_panel.parquet", args.country_sample), "growth panel", flow)
    growth = merge_world(growth_base, world, "growth")

    ex2 = pd.DataFrame()
    if flow == "Exports":
        ex2_base = load_flow_panel(
            sample_processed_path("exercise_02_bucket_growth_panel.parquet", args.country_sample), "Exercise 2 growth panel", flow
        )
        ex2 = merge_world(ex2_base, world, "Exercise 2 growth")

    ex11_country_year = load_ex11_country_year()
    controls = country_size_base[
        ["reporter_code", "year", "product_gini", "log_population", "log_gdp_per_capita"]
    ].drop_duplicates(["reporter_code", "year"])
    ex11 = (
        merge_world(ex11_country_year, world, "Exercise 11 aggregate")
        .merge(controls, on=["reporter_code", "year"], how="left", validate="many_to_one")
    )

    model_frames = [
        run_country_size_models(country_size, flow),
        run_growth_models(growth, flow),
        run_intermediate_import_models(ex11, flow),
    ]
    if flow == "Exports":
        model_frames.insert(2, run_exercise2_growth_models(ex2))
    all_models = pd.concat(model_frames, ignore_index=True)
    key = key_coefficients(all_models)
    diagnostic_frames = {
        "country_size_common_world_relative": country_size,
        "growth_common_world_relative": growth,
        "exercise_11_aggregate_common_world_relative": ex11,
    }
    if flow == "Exports":
        diagnostic_frames["exercise_02_common_world_relative"] = ex2
    diagnostics = sample_diagnostics(
        diagnostic_frames,
        flow,
    )

    prefix = "world_relative_exercise_robustness" if flow == "Exports" else "world_relative_import_exercise_robustness"
    all_path = result_dir / f"{prefix}_models.csv"
    key_path = result_dir / f"{prefix}_key_coefficients.csv"
    diag_path = result_dir / f"{prefix}_sample_diagnostics.csv"
    memo_path = result_dir / f"{prefix}.md"
    manifest_path = result_dir / f"run_manifest_{prefix}.json"

    all_models.to_csv(all_path, index=False)
    key.to_csv(key_path, index=False)
    diagnostics.to_csv(diag_path, index=False)
    output_paths = {"all models": all_path, "key coefficients": key_path, "sample diagnostics": diag_path}
    write_memo(memo_path, key, diagnostics, output_paths, flow)
    included_components = [
        "country_size_direct_outcome_swap",
        "growth_effect_direct_outcome_swap",
        "exercise_11_aggregate_import_structure_followup",
    ]
    skipped_components: list[dict[str, str]] = []
    if flow == "Exports":
        included_components.insert(2, "exercise_2_export_bucket_growth")
    else:
        skipped_components.append(
            {
                "component": "exercise_2_export_bucket_growth",
                "reason": "Exercise 2 bucket-growth source data are export-only and are not reused as an import analog.",
            }
        )

    manifest = {
        "created_at_utc": now_utc(),
        "country_sample": args.country_sample,
        "flow": flow,
        "benchmark_flow": flow,
        "world_relative_source": rel(
            sample_results_dir(args.country_sample) / tables_dirname(flow) / f"{artifact_stem(flow)}_all_years.csv"
        ),
        "product_harmonization": {
            "method": "official LT/HGL weighted conversion to HS1992/H0",
            "source_doi": "10.7910/DVN/6AADMR",
            "source_version": "2.1",
        },
        "outputs": {label: rel(path) for label, path in {**output_paths, "memo": memo_path}.items()},
        "row_counts": {
            "all_models": int(len(all_models)),
            "key_coefficients": int(len(key)),
            "sample_diagnostics": int(len(diagnostics)),
        },
        "sample_rows": diagnostics.to_dict(orient="records"),
        "included_components": included_components,
        "skipped_components": skipped_components,
        "notes": [
            "Country-size and growth are direct country-year outcome swaps.",
            "Exercise 2 uses world-relative Gini as an initial continuous concentration predictor in the export-only run.",
            "Exercise 11 is an aggregate follow-up because the original product-level exercise has no direct world-relative country-year replacement.",
            "For the import run, growth-effect models use export-growth controls with import concentration outcomes and should be read as cross-flow descriptive evidence.",
        ],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {rel(memo_path)}")
    print(f"Wrote {rel(key_path)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--country-sample", default=COUNTRY_SAMPLE, choices=(COUNTRY_SAMPLE,))
    parser.add_argument("--flow", default="Exports", choices=FLOW_CHOICES)
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
